# NOTE: See example file for possible S3 deployment
language:
  - node_js
node_js:
  - 5
install:
  - travis_retry npm install
before_script: webpack
script:
  - "npm run test"
cache:
  directories:
    - node_modules
